FROM python:3.11-alpine

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "main.py"]
