services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: "{WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "{WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "{WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "{WORDPRESS_DB_PASSWORD}"
    ports:
      - "8080:80"
    networks:
      - wordpress-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: "{MYSQL_DATABASE}"
      MYSQL_USER: "{MYSQL_USER}"
      MYSQL_PASSWORD: "{MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "{MYSQL_ROOT_PASSWORD}"
    networks:
      - wordpress-network
    volumes:
      - mysql-db-data:/var/lib/mysql
networks:
  wordpress-network:

volumes:
  mysql-db-data:
